// <auto-generated />
using System;
using Commercify.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Commercify.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101110620_AddProduct")]
    partial class AddProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commercify.Core.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Devices and gadgets for everyday use",
                            LastUpdatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Apparel for men, women, and children",
                            LastUpdatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Appliances to improve home living",
                            LastUpdatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Literature across genres and interests",
                            LastUpdatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Toys and games for children of all ages",
                            LastUpdatedAt = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("Commercify.Core.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("stockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Commercify.Core.Models.Product", b =>
                {
                    b.HasOne("Commercify.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Commercify.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
