services:
  commercify.api:
    image: commercify.api
    build:
      context: .
      dockerfile: src/Commercify.API/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        commercify.database:
            condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    networks:
       - commercify-network
  commercify.database:
    image: postgres:latest
    container_name: commercify.database
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=commercify
    volumes:
        - ./.containers/commercify.database:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
        - commercify-network
    healthcheck:
        test: ["CMD-SHELL","pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
        - "5050:80"
    depends_on:
        commercify.database:
            condition: service_healthy
    networks:
        - commercify-network

networks:
    commercify-network:
        driver: bridge


